# Generated by Django 4.2.5 on 2023-09-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduser',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
